changed look of social media to mirror press page
vricci518/barbill pull request #47
Opened 2021-03-05 01:14 UTC by margeschrec

-also Vincent found that the barbill tavern google map link on footer was the same as the takeout- 
changed that to link to the tavern instead. 
-trimmed FAQ heading tag to match the rest of the sites headings. 
closes #46

2021-03-05 01:20 UTC, vricci518 approved these changes

2021-03-05 01:41 UTC, billythakidd04 requested changes
I think you guys are getting a little nutty with the individual css files but thats a personal choice. code looks good tho

2021-03-06 19:46 UTC, margeschrec commented
> I think you guys are getting a little nutty with the individual css files but thats a personal choice. code looks good tho

I hear you, something to consider going forward.

2021-03-06 22:22 UTC, billythakidd04 approved these changes

2021-03-07 18:50 UTC, merged